# Generated by Django 6.0.4 on 2026-05-08 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_bundle_discount_product_is_bundle_bundleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Announcement text to display', max_length=500)),
                ('link_url', models.URLField(blank=True, help_text='Optional link for the announcement', null=True)),
                ('link_text', models.CharField(blank=True, help_text="Link text (e.g., 'Shop Now')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide announcement bar')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('background_color', models.CharField(default='#f0a500', help_text='Hex color code', max_length=20)),
                ('text_color', models.CharField(default='#000000', help_text='Hex color code', max_length=20)),
                ('show_icon', models.BooleanField(default=True, help_text='Show/hide icon (🎁, 🚚, ✨, 💳)')),
                ('icon', models.CharField(blank=True, choices=[('🎁', '🎁 Gift'), ('🚚', '🚚 Delivery'), ('✨', '✨ Special'), ('💳', '💳 Payment'), ('⚡', '⚡ Flash'), ('🔥', '🔥 Hot'), ('⭐', '⭐ Featured')], help_text='Emoji icon (e.g., 🎁, 🚚, ✨, 💳)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement Bar',
                'verbose_name_plural': 'Announcement Bars',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Flash Sale — Up to 50% Off', max_length=200)),
                ('subtitle', models.CharField(default='Limited time offer on selected northern crafts & dried fruits', max_length=300)),
                ('discount_percentage', models.IntegerField(default=50, help_text='Discount percentage to show', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('start_date', models.DateTimeField(help_text='When the flash sale starts')),
                ('end_date', models.DateTimeField(help_text='When the flash sale ends')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide flash sale')),
                ('background_color', models.CharField(default='#7c1a1a', help_text='Hex color code', max_length=20)),
                ('button_text', models.CharField(default='Grab Deals', max_length=50)),
                ('button_link', models.CharField(default='/products?sale=true', max_length=200)),
                ('show_countdown', models.BooleanField(default=True, help_text='Show/hide countdown timer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Products included in flash sale (leave empty to show all products with sale tag)', related_name='flash_sales', to='products.product')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'ordering': ['-is_active', '-start_date'],
            },
        ),
    ]
