# Generated by Django 6.0.4 on 2026-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Textile Weaving', max_length=100)),
                ('badge_text', models.CharField(default='Master Artisan', max_length=100)),
                ('title', models.CharField(default='The Art of Traditional Weaving', max_length=300)),
                ('story_text', models.TextField(default='')),
                ('quote_text', models.TextField(default='')),
                ('author_name', models.CharField(default='', max_length=200)),
                ('author_role', models.CharField(default='', max_length=200)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('reverse_layout', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artisan Story',
                'verbose_name_plural': 'Artisan Stories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Become Part of Our Story', max_length=300)),
                ('highlighted_word', models.CharField(default='Story', max_length=100)),
                ('text', models.TextField(default="When you shop with us, you're not just buying a product—you're supporting families, preserving traditions, and celebrating the beauty of handcrafted excellence")),
                ('button_text', models.CharField(default='Explore Our Collection', max_length=100)),
                ('button_link', models.CharField(default='/products', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Est. in Gilgit-Baltistan', max_length=200)),
                ('title', models.CharField(default='Crafted with Love, Rooted in Tradition', max_length=500)),
                ('subtitle', models.TextField(default='Every product tells a story of heritage, craftsmanship, and the breathtaking beauty of Gilgit-Baltistan')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='IntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Where Mountains Meet Mastery', max_length=300)),
                ('highlighted_word', models.CharField(default='Mastery', max_length=100)),
                ('text_paragraph_1', models.TextField(default="Nestled in the heart of Pakistan's northern highlands, Gilgit-Baltistan is more than just a place—it's a living testament to centuries of artisan tradition and cultural richness.")),
                ('text_paragraph_2', models.TextField(default='Our journey began with a simple vision: to connect the world with the extraordinary craftsmanship of our local artisans, farmers, and makers who pour their hearts into every creation.')),
                ('quote_text', models.TextField(default='Each product carries the soul of its maker, the essence of our mountains, and a commitment to preserving traditions that have been passed down through generations.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='intro/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intro Section',
                'verbose_name_plural': 'Intro Sections',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='process/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(choices=[('Users', 'Users'), ('Mountain', 'Mountain'), ('Heart', 'Heart'), ('Award', 'Award')], default='Users', max_length=50)),
                ('value', models.CharField(default='0', max_length=50)),
                ('label', models.CharField(default='', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_eyebrow_text', models.CharField(default='Meet Our Makers', max_length=200)),
                ('section_title', models.CharField(default='Stories of Passion and Pride', max_length=300)),
                ('section_title_word_1', models.CharField(default='Passion', max_length=100)),
                ('section_title_word_2', models.CharField(default='Pride', max_length=100)),
                ('section_subtitle', models.TextField(default='Behind every product is a person, a family, and a legacy of craftsmanship')),
                ('process_eyebrow_text', models.CharField(default='From Mountain to Market', max_length=200)),
                ('process_title', models.CharField(default='Our Creation Process', max_length=300)),
                ('process_title_word', models.CharField(default='Creation', max_length=100)),
                ('process_subtitle', models.TextField(default='Every product goes through a careful journey of craftsmanship and quality assurance')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Story Settings',
                'verbose_name_plural': 'Story Settings',
            },
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='See Our Craft Come to Life', max_length=300)),
                ('highlighted_word', models.CharField(default='Craft', max_length=100)),
                ('subtitle', models.TextField(default='Watch how our artisans transform raw materials into beautiful, handcrafted products that tell a story')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='video/')),
                ('youtube_video_id', models.CharField(default='dQw4w9WgXcQ', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Section',
                'verbose_name_plural': 'Video Sections',
            },
        ),
    ]
