# Generated by Django 6.0.4 on 2026-05-04 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupon_discount_coupon_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=300, help_text='Standard shipping cost in PKR', max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g., 2 for 2%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_name', models.CharField(choices=[('gst', 'GST'), ('vat', 'VAT'), ('sales_tax', 'Sales Tax'), ('pst', 'PST')], default='GST', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
                'db_table': 'store_settings',
            },
        ),
    ]
