# Generated by Django 6.0.4 on 2026-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Business Hour',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(choices=[('Phone', 'Phone'), ('Mail', 'Mail'), ('MapPin', 'Map Pin'), ('MessageCircle', 'Message Circle')], default='Phone', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Channel',
                'verbose_name_plural': 'Contact Channels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_eyebrow', models.CharField(default='Message Us', max_length=100)),
                ('title_prefix', models.CharField(default='Send a', max_length=200)),
                ('title_highlight', models.CharField(default='Message', max_length=100)),
                ('subtitle', models.TextField(default='Fill out the form below and our team will get back to you within 24 hours.')),
                ('subject_types', models.JSONField(default=list, help_text='List of subject types for the form')),
                ('name_label', models.CharField(default='Full Name', max_length=50)),
                ('email_label', models.CharField(default='Email Address', max_length=50)),
                ('subject_label', models.CharField(default='Subject', max_length=50)),
                ('message_label', models.CharField(default='Message', max_length=50)),
                ('name_placeholder', models.CharField(default='e.g. Ahmed Raza', max_length=100)),
                ('email_placeholder', models.CharField(default='hello@example.com', max_length=100)),
                ('subject_placeholder', models.CharField(default='{type} — describe briefly', max_length=200)),
                ('message_placeholder', models.CharField(default='Tell us exactly how we can help you…', max_length=200)),
                ('max_message_length', models.IntegerField(default=500)),
                ('privacy_text', models.TextField(default='Your data is protected and will never be shared with third parties.')),
                ('button_loading_text', models.CharField(default='Sending your message…', max_length=100)),
                ('button_sent_text', models.CharField(default='Message Sent! ✓', max_length=100)),
                ('button_default_text', models.CharField(default='Send Message', max_length=100)),
                ('success_toast_message', models.TextField(default="Message sent! We'll get back to you within 24 hours.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form Settings',
                'verbose_name_plural': 'Contact Form Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default="We're here for you", max_length=200)),
                ('title_line_1', models.CharField(default="Let's Start", max_length=200)),
                ('title_highlight', models.CharField(default='a Conversation', max_length=100)),
                ('subtitle', models.TextField(default='Questions about an order, a product, or want to become an artisan partner? Our dedicated team is ready to help — fast, friendly, and from the heart.')),
                ('response_pills', models.JSONField(default=list, help_text='List of response pills e.g., ["Avg. reply in 3 hrs", "98% satisfaction rate", "Secure & confidential"]')),
                ('quick_links', models.JSONField(default=list, help_text='Quick links e.g., [{"icon":"Phone","text":"Call Now","link":"tel:+923451234567"}]')),
                ('hero_cards', models.JSONField(default=list, help_text='Cards for hero visual')),
                ('online_indicator_text', models.CharField(default='Support team is online now — ready to help', max_length=300)),
                ('online_indicator_highlight', models.CharField(default='online now', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Hero Section',
                'verbose_name_plural': 'Contact Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_column_eyebrow', models.CharField(default='Contact', max_length=100)),
                ('info_column_title_prefix', models.CharField(default='Get in', max_length=200)),
                ('info_column_title_highlight', models.CharField(default='Touch', max_length=100)),
                ('info_column_subtitle', models.TextField(default="Whether it's a question, feedback, or a fresh partnership idea — pick the channel that works best for you.")),
                ('hours_section_title', models.CharField(default='Business Hours', max_length=100)),
                ('social_section_title', models.CharField(default='Follow Us', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='MapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(default='Find', max_length=200)),
                ('title_highlight', models.CharField(default='Us', max_length=100)),
                ('subtitle', models.TextField(default='Operating from the stunning highlands of northern Pakistan')),
                ('map_embed_url', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d211174.78!2d74.3!3d35.9!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38e649c0aa418e67%3A0x87b2ed80018aa1e8!2sGilgit-Baltistan%2C%20Pakistan!5e0!3m2!1sen!2s!4v1234567890123!5m2!1sen!2s')),
                ('map_link_text', models.CharField(default='Open in Maps', max_length=100)),
                ('map_link_url', models.URLField(default='https://maps.google.com/?q=Gilgit-Baltistan,Pakistan')),
                ('map_footer_items', models.JSONField(default=list, help_text='Footer items for map section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map Section',
                'verbose_name_plural': 'Map Sections',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('TW', 'Twitter'), ('YT', 'YouTube'), ('LI', 'LinkedIn')], max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_display', models.CharField(help_text='Display text for icon (e.g., FB, IG)', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
    ]
