# Generated by Django 6.0.4 on 2026-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('FaFacebook', 'FaFacebook'), ('IG', 'FaInstagram'), ('TW', 'FaTwitter'), ('YT', 'FaYouTube'), ('LI', 'FaLinkedIn')], max_length=10),
        ),
    ]
