# Generated by Django 6.0.4 on 2026-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_sociallink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('FaFacebook', 'FaFacebook'), ('FaInstagram', 'FaInstagram'), ('FaTwitter', 'FaTwitter'), ('FaYouTube', 'FaYouTube'), ('FaLinkedIn', 'FaLinkedIn')], max_length=20),
        ),
    ]
