# Generated by Django 6.0.4 on 2026-05-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Preserving heritage since 2020', max_length=200)),
                ('title_line_1', models.CharField(default='The Heart Behind', max_length=200)),
                ('title_highlight', models.CharField(default='Gilgit Bazaar', max_length=100)),
                ('subtitle', models.TextField(default='We bridge the majestic highlands of Gilgit-Baltistan with the world — connecting skilled artisans, organic farmers, and centuries-old traditions directly to your doorstep.')),
                ('cta_button_text', models.CharField(default='Explore Products', max_length=100)),
                ('cta_button_link', models.CharField(default='/products', max_length=500)),
                ('secondary_cta_text', models.CharField(default='Our Story', max_length=100)),
                ('secondary_cta_link', models.CharField(default='#story', max_length=500)),
                ('trust_pills', models.JSONField(default=list, help_text='List of trust badges e.g., ["Gilgit-Baltistan, PK", "100% Authentic", "Ethically Sourced"]')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('floating_card_top_value', models.CharField(default='100+', max_length=50)),
                ('floating_card_top_label', models.CharField(default='Artisan Partners', max_length=100)),
                ('floating_card_bottom_value', models.CharField(default='4.9★', max_length=50)),
                ('floating_card_bottom_label', models.CharField(default='Customer Rating', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Hero Section',
                'verbose_name_plural': 'About Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_eyebrow', models.CharField(default='What We Stand For', max_length=100)),
                ('values_title', models.CharField(default='Our Core Values', max_length=200)),
                ('values_title_highlight', models.CharField(default='Values', max_length=100)),
                ('values_subtitle', models.TextField(default='The principles that guide every decision, partnership, and product we offer')),
                ('timeline_eyebrow', models.CharField(default='Milestones', max_length=100)),
                ('timeline_title', models.CharField(default='Our Journey', max_length=200)),
                ('timeline_title_highlight', models.CharField(default='Journey', max_length=100)),
                ('timeline_subtitle', models.TextField(default="From a bold idea in 2020 to Pakistan's premier highland marketplace")),
                ('team_eyebrow', models.CharField(default='The People', max_length=100)),
                ('team_title', models.CharField(default='Meet the Team', max_length=200)),
                ('team_title_highlight', models.CharField(default='Team', max_length=100)),
                ('team_subtitle', models.TextField(default='Passionate individuals dedicated to sharing the magic of Gilgit-Baltistan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ArtisanSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Artisan Spotlight', max_length=100)),
                ('title_prefix', models.CharField(default='The Hands That Create', max_length=200)),
                ('title_highlight', models.CharField(default='Magic', max_length=100)),
                ('description', models.TextField(default='Behind every product is a skilled artisan from the remote valleys of Hunza, Skardu, and Nagar. We ensure fair wages, ethical sourcing, and active preservation of traditional techniques that have been refined over centuries.')),
                ('features', models.JSONField(default=list, help_text='List of feature badges')),
                ('cta_text', models.CharField(default='Support Artisans', max_length=100)),
                ('cta_link', models.CharField(default='/products?category=handicrafts', max_length=500)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/spotlight/')),
                ('secondary_image_1', models.ImageField(blank=True, null=True, upload_to='about/spotlight/')),
                ('secondary_image_2', models.ImageField(blank=True, null=True, upload_to='about/spotlight/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artisan Spotlight',
                'verbose_name_plural': 'Artisan Spotlights',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Stay in Touch', max_length=100)),
                ('title_prefix', models.CharField(default='Stay', max_length=200)),
                ('title_highlight', models.CharField(default='Connected', max_length=100)),
                ('description', models.TextField(default='Be first to hear about new artisans, collections, and cultural stories from the highlands of Gilgit-Baltistan.')),
                ('button_text', models.CharField(default='Subscribe', max_length=100)),
                ('social_links', models.JSONField(default=dict, help_text='Social media links e.g., {"FB": "https://facebook.com", "IG": "https://instagram.com"}')),
                ('social_labels', models.JSONField(default=list, help_text='Social media labels e.g., ["FB", "IG", "TW", "YT"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Section',
                'verbose_name_plural': 'Newsletter Sections',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('icon_name', models.CharField(choices=[('Star', 'Star'), ('Heart', 'Heart'), ('Users', 'Users'), ('Award', 'Award'), ('TrendingUp', 'Trending Up'), ('Clock', 'Clock')], default='Star', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistic Item',
                'verbose_name_plural': 'Statistic Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Our Story', max_length=100)),
                ('title_prefix', models.CharField(default='Roots in the', max_length=200)),
                ('title_highlight', models.CharField(default='Mountains', max_length=100)),
                ('title_suffix', models.CharField(default='Reach to the World', max_length=200)),
                ('paragraph_1', models.TextField(default="Founded in 2020, Gilgit Bazaar was born from a deep love for the breathtaking landscapes and extraordinary craftsmanship of Gilgit-Baltistan. What began as a small initiative to help local artisans reach wider markets has grown into a thriving platform celebrating the soul of Pakistan's north.")),
                ('quote_text', models.TextField(default='Every product tells a story of hands that shaped it, valleys it came from, and traditions passed down for generations.')),
                ('paragraph_2', models.TextField(default='We work hand-in-hand with local communities — from weavers in Hunza to farmers in Skardu — ensuring fair wages, ethical sourcing, and a direct line between maker and buyer.')),
                ('check_items', models.JSONField(default=list, help_text='List of checkmark items')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about/story/')),
                ('badge_year', models.CharField(default='2020', max_length=10)),
                ('badge_label', models.CharField(default='Year Founded', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Story Section',
                'verbose_name_plural': 'Story Sections',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/team/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Item',
                'verbose_name_plural': 'Timeline Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(choices=[('Heart', 'Heart'), ('Award', 'Award'), ('Users', 'Users'), ('Target', 'Target'), ('Shield', 'Shield'), ('Globe', 'Globe')], default='Heart', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['order'],
            },
        ),
    ]
