# Generated by Django 6.0.4 on 2026-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discount percentage for the bundle', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='Is this a gift hamper/bundle?'),
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_bundles', to='products.product')),
            ],
            options={
                'db_table': 'bundle_items',
                'unique_together': {('bundle', 'product')},
            },
        ),
    ]
